Explicitly load the zcml of plone.restapi.
Otherwise you get an error in the tests:

```
KeyError: 'Profile "profile-osha.oira:default" requires the dependency-profile "profile-plone.restapi:default", which does not exist.'
```