Remove an unused module
It has a broken import:

```
>>> from osha.oira import patch
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/ale/Code/plone/projects/quoira/oira/src/osha.oira/src/osha/oira/patch.py", line 4, in <module>
    from plone.app.upgrade.v43 import alphas
ModuleNotFoundError: No module named 'plone.app.upgrade.v43'
```